# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :title
relative_permalinks: true

# Setup
title:               Python Study Groups
tagline:             'Resources for people learning Python'
description:         'A collection of curated Python resources and exercises.'
url:                 http://pythonstudygroup.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Jennie Lees
  url:               https://twitter.com/jennielees
  email:             jennielees@gmail.com

# Custom vars
version:             1.0.0

github:
  repo:             http://github.com/pythonstudygroup